package olupis.world.blocks.calyx;

import arc.*;
import arc.audio.*;
import arc.func.*;
import arc.graphics.*;
import arc.graphics.g2d.*;
import arc.math.*;
import arc.struct.*;
import arc.util.*;
import mindustry.content.*;
import mindustry.entities.*;
import mindustry.game.*;
import mindustry.gen.*;
import mindustry.graphics.*;
import mindustry.world.*;
import mindustry.world.blocks.environment.*;
import olupis.content.*;
import olupis.world.blocks.calyx.ineternal.*;

import static mindustry.Vars.*;
import static olupis.NyfalisVars.nyfRule;
import static olupis.world.EnvUpdater.*;
import static olupis.world.NyfWorldFuckingHelper.spreadLevels;

public class SpreadingOverlay extends OverlayFloor implements UpdatingEnvironment{
    public static final int arrayID = 1;

    /** Default replacement block */
    public Block replacement = Blocks.air;
    /** The amount of times the chance must be rolled */
    public byte spreadTries = 3;
    /** Base chance for the tile to try to spread, updated every second */
    public double spreadChance = 0.013 / 60f;
    /** Base chance for the tile to try to Upgrade, updated every second */
    public double growChance = 0.013 / 60f;
    /** Whether this block spreads to all surrounding tiles */
    public boolean spread = false;

    /** The sound played when this spreads */
    public Sound spreadSound = null;
    /** Volume at which the spreadSound plays */
    public float spreadVolume = 0.13f;
    /** An effect spawned at the target tile when spreading */
    public Effect spreadEffect = NyfalisFxs.mossSpread,
    /** An effect this spawns when it upgrades */
    upgradeEffect = NyfalisFxs.mossSpread;
    public Color upgradeColor = Color.clear;

    /** Spreading blacklist */
    public ObjectSet<Block> blacklist = ObjectSet.with(Blocks.coreZone);
    /** String used to get the blacklist ObjectSet from EnvUpdater, also used for spread level list generation */
    public String blacklistKey = "default";
    public Func<Block, Boolean>
        validator = t ->
            !blacklist(blacklistKey).contains(t)
            && !(t instanceof Calyxian)
            && !t.isStatic()
            && !(t instanceof Floor f && f.isLiquid),
        filter = t ->
            validator.get(t)
            && !(t instanceof SpreadingOverlay)
            && !(t instanceof SpreadingOre);

    /** A list of replacements for floors, stock block first, then replacement */
    public OrderedMap<Block, Block> replacements = new OrderedMap<>();
    /** Block this can "upgrade" into, upgrading takes just as long as spreading */
    public Block next = null;

    /** Efficiency of drills on ores converted by this floor, set to -1 in order to manually adjust for each ore, otherwise this value will be set for each */
    public float drillEfficiency = 1f;

    /** Random props or other blocks that may spawn on the moss when it grows - only applies to this specific floor type */
    public Seq<Block> props = new Seq<>();
    /** Whether ores generated by this overlay spawn props */
    public boolean oresSpawnProps = false;
    /** The chance that a random prop will spawn */
    public double spawnChance = 0.01d;
    /** Prop spawn limit for this floor type */
    public int propLimit = 150;
    /** Additional value added to the propLimit for every single accessible world tile, 0 to disable */
    public float dynamicLimit = 0;

    /** Contains ores generated by this floor */
    public Seq<SpreadingOre> ores = new Seq<>();
    /** Prefix used by ore generation**/
    public String orePrefix;

    /**Requires a Calyx graph with an active heart to spread **/
    public boolean spreadRequiresHeart = true;
    /** Range from a calyx network to grow to consider alive**/
    public int connectionRange = 8 * tilesize;
    /**List of building that can grow on this tile **/
    public Seq<Block> sprouts = new Seq<>();
    /** Base chance for the tile to try to sprout a building, updated every second */
    public double sproutChance = 0.013 / 60f;
    /** how unlikely a tile will get a sprout if there already crowded. -1 to disable */
    public float sproutAdjacentPenalty = 0.8f;

    public Color noHeartColour = Pal.accentBack;

    public SpreadingOverlay(String name, int variants){
        super(name);

        this.variants = variants;
        this.orePrefix = Core.bundle.get(getContentType() + "." + this.name + ".ore-prefix", this.name);

        Events.on(EventType.ModContentLoadEvent.class, e -> {
            generate();

            Core.app.post(() -> {
                if(next instanceof SpreadingOverlay f){
                    for(int i = 0; i < ores.size; i++)
                        ores.get(i).next = f.ores.get(i);

                    return;
                }

                ores.each(o -> o.set = next);
            });
        });

        Events.on(EventType.ServerLoadEvent.class, e ->
            blacklist = blacklist(blacklistKey)
        );
        Events.on(EventType.ClientLoadEvent.class, e -> {
            blacklist = blacklist(blacklistKey);

            int idx = replacements.values().toSeq().indexOf(ores.first());
            Seq<Block> vanilla = replacements.keys().toSeq();

            for(int i = 0; i < ores.size; i++){
                ores.get(i).uiIcon = vanilla.get(i + idx).uiIcon;
                ores.get(i).fullIcon = vanilla.get(i + idx).fullIcon;
                ores.get(i).variants = vanilla.get(i + idx).variants;
                ores.get(i).variantRegions = vanilla.get(i + idx).variantRegions;
                ores.get(i).overlayRegions = variantRegions;
                ores.get(i).mapColor.shiftValue(-0.05f * spreadLevels.get(this));
                ores.get(i).localizedName = Strings.format("[#@]@[] @", mapColor.toString(), orePrefix, vanilla.get(i + idx).localizedName);
            }
        });
    }

    @Override
    public void init(){
        ObjectSet<Block> list = blacklist(blacklistKey);
        if(list.isEmpty())
            spreadLevels.put(this, 1);

        blacklist.each(entry -> {
            if(!list.contains(entry)){
                list.add(entry);
            }
        });
    }

    @Override
    public boolean isOverlay(){
        return true;
    }

    public void generate(){
        content.blocks().select(b -> b instanceof OreBlock o && !o.wallOre && !(b instanceof SpreadingOre)).each(o -> {
            SpreadingOre ore = new SpreadingOre(getName(o));

            ore.itemDrop = o.itemDrop;
            ore.mapColor.set(o.itemDrop.color).sub(0, 0, 0,  0.45f);

            ore.parent = this;

            replacements.put(o, ore);
            ores.add(ore);
        });
    }

    @Override
    public void drawBase(Tile tile){
        if(!isAlive(tile)) Draw.color(noHeartColour, 0.5f);
        Draw.rect(
            variantRegions[Mathf.randomSeed(tile.pos(), 0, Math.max(0, variantRegions.length - 1))],
            tile.worldx(),
            tile.worldy(),
            Mathf.randomSeed(tile.pos(),0, 3) * 90f
        );
        Draw.reset();
    }

    public String getName(Block in){
        return in.name.replaceAll("ore-|olupis-|nyfalis-", "") + name.replaceAll("olupis|nyfalis|-overlay", "");
    }

    @Override
    public void lazyEnv(Tile tile){
        Building heart =Units.closestBuilding(nyfRule.calyxTeam, tile.x * tilesize , tile.y * tilesize, connectionRange, b -> !b.dead && b instanceof  Calyxian c && c.isAlive());
        if(heart != null) aliveOverlays.add(tile.pos());
        else aliveOverlays.removeValue(tile.pos());
    }

    @Override
    public void updateEnv(Tile tile, EnvStruct i){
        if(net.client()) return;

        boolean
            growth =
                isAlive(tile)
                && Mathf.chance(growChance * nyfRule.calyxGrowthFactor) ,
            spreads= isAlive(tile) && nyfRule.calyxSpreading && Mathf.chance(spreadChance * nyfRule.calyxSpreadingFactor),
            sprout = sprouts.any()
                && (tile.block() == Blocks.air || (tile.block().alwaysReplace) || (tile.block().unitMoveBreakable))
                && isAlive(tile) &&  adjacentCalyxian(tile)
                && Mathf.chance(sproutChance * nyfRule.calyxSproutFactor);

        if( (growth || spreads || sprout) && i.getIncrementFloor() >= spreadTries){
            i.clearFloorVal();

            if(next != null && growth){
                if(upgradeEffect != null){
                    tasks.post(() -> {
                        upgradeEffect.at(tile.worldx(), tile.worldy(), 0f, upgradeColor);
                        Call.effect(upgradeEffect, tile.worldx(), tile.worldy(), 0, upgradeColor);
                    });
                }

                if(spreadSound != null)
                    tasks.post(() -> Call.soundAt(spreadSound, tile.worldx(), tile.worldy(), spreadVolume, 1f));

                queue(next).add(tile.pos());

                if(props.size > 0 && canSpawn(id, propLimit, dynamicLimit) && Mathf.chance(spawnChance)){
                    addProp(id);
                    queue(props.random()).add(tile.pos());
                }
            }

            if(spread && spreads){
                for(int it = 0; it < 4; it++){
                    Tile near = tile.nearby(it);
                    if(near == null)
                        continue;

                    EnvStruct nearby = instances[near.array()];
                    if(replaces(near, nearby) || !canSpread(near))
                        continue;

                    if(nearby.canWriteFloor())
                        nearby.setFloorIndex(near.overlay());
                    queue(this).add(near.pos());

                    if(spreadEffect != null){
                        tasks.post(() -> {
                            spreadEffect.at(near.worldx(), near.worldy(), near.floor().mapColor);
                            Call.effect(spreadEffect, near.worldx(), near.worldy(), 0, near.floor().mapColor);
                        });
                    }
                }
            }

            if(sprout){

                Seq<Block> out = sprouts.copy();
                out.retainAll( b -> b.canPlaceOn(tile, nyfRule.calyxTeam, 0));
                if(out.any()){

                    if(upgradeEffect != null){
                        tasks.post(() -> {
                            upgradeEffect.at(tile.worldx(), tile.worldy(), 0f, upgradeColor);
                            Call.effect(upgradeEffect, tile.worldx(), tile.worldy(), 0, upgradeColor);
                        });
                    }

                    if(spreadSound != null) tasks.post(() -> Call.soundAt(spreadSound, tile.worldx(), tile.worldy(), spreadVolume, 1f));
                    tile.setBlock(out.random(), nyfRule.calyxTeam, 0);
                }
            }
        }
    }

    public boolean replaces(Tile tile, EnvStruct i){
        boolean replaces = false;

        Block tileBlock = tile.floor();
        Block block = replacements.get(tileBlock);
        if(block != null){
            replaces = true;

            if(i.canWriteFloor())
                i.setFloorIndex(tileBlock);
            queue(block).add(tile.pos());
        }

        tileBlock = tile.overlay();
        block = replacements.get(tileBlock);
        if(block != null){
            replaces = true;

            if(i.canWriteOverlay())
                i.setOverlayIndex(tileBlock);
            queue(block).add(tile.pos());
        }

        tileBlock = tile.block();
        block = replacements.get(tileBlock);
        if(block != null){
            replaces = true;

            if(i.canWriteBlock())
                i.setBlockIndex(tileBlock);
            queue(block).add(tile.pos());
        }

        return replaces;
    }

    public boolean adjacentCalyxian(Tile tile){
        int near = 0;
        for(int i = 0; i <= 3; i++){
            if(tile.nearbyBuild(i) == null) continue;
            if(tile.nearbyBuild(i) instanceof Calyxian cal && cal.isAlive()){
                if(sproutAdjacentPenalty <= -1) return true;
                near++;
            }
        }
        if(near == 0) return false;
        return Mathf.chance(sproutAdjacentPenalty / near);
    }

    public boolean canSpread(Tile tile){
        return(
            filter.get(tile.floor())
            && filter.get(tile.overlay())
            && filter.get(tile.block())
        );
    }

    public boolean isValid(Tile tile){
        return(
            validator.get(tile.floor())
            && validator.get(tile.overlay())
            && validator.get(tile.block())
        );
    }

    public boolean isAlive(Tile tile){
        return !spreadRequiresHeart || aliveOverlays.contains(tile.pos());
    }

    public Block replacement(){
        return replacement;
    }
}