package olupis.world.blocks.environment;

import arc.*;
import arc.audio.*;
import arc.func.*;
import arc.graphics.g2d.*;
import arc.math.*;
import arc.struct.*;
import arc.util.*;
import mindustry.content.*;
import mindustry.entities.*;
import mindustry.game.*;
import mindustry.gen.*;
import mindustry.world.*;
import mindustry.world.blocks.environment.*;
import olupis.content.*;

import static mindustry.Vars.*;
import static olupis.NyfalisVars.*;
import static olupis.world.EnvUpdater.*;

public class SpreadingOverlay extends OverlayFloor implements UpdatingEnvironment{
    public static final int arrayID = 1;

    /** Default replacement block */
    public Block replacement = Blocks.air;
    /** The amount of times the chance must be rolled */
    public byte spreadTries = 3;
    /** Base chance for the tile to try to spread, updated every second */
    public double spreadChance = 0.013 / 60f;
    /** Whether this block spreads to all surrounding tiles */
    public boolean spread = false;

    /** The sound played when this spreads */
    public Sound spreadSound = null;
    /** An effect spawned at the target tile when spreading */
    public Effect spreadEffect = NyfalisFxs.mossSpread, //NyfalisFxs.highYieldExplosive,
    /** An effect this spawns when it upgrades */
    upgradeEffect = NyfalisFxs.mossStageUp; //NyfalisFxs.impactReactorExplosion;

    /** Spreading blacklist */
    public ObjectSet<Block> blacklist = ObjectSet.with(Blocks.coreZone);
    public String blacklistKey = "default";
    public Func<Block, Boolean>
        validator = t ->
            !blacklist(blacklistKey).contains(t)
            && !t.isStatic()
            && !(t instanceof Floor f && f.isLiquid),
        filter = t ->
            validator.get(t)
            && !(t instanceof SpreadingOverlay)
            && !(t instanceof SpreadingOre);

    /** A list of replacements for floors, stock block first, then replacement */
    public OrderedMap<Block, Block> replacements = new OrderedMap<>();
    /** Block this can "upgrade" into, upgrading takes just as long as spreading */
    public Block next = null;

    /** Efficiency of drills on ores converted by this floor, set to -1 in order to manually adjust for each ore, otherwise this value will be set for each */
    public float drillEfficiency = 1f;

    /** Random props or other blocks that may spawn on the moss when it grows - only applies to this specific floor type */
    public Seq<Block> props = new Seq<>();
    /** Whether ores generated by this overlay spawn props */
    public boolean oresSpawnsProps = false;
    /** The chance that a random prop will spawn */
    public double spawnChance = 0.01d;
    /** Prop spawn limit for this floor type */
    public int propLimit = 150;
    /** Additional value added to the propLimit for every single accessible world tile, 0 to disable */
    public float dynamicLimit = 0;

    /** Contains ores generated by this floor */
    public Seq<SpreadingOre> ores = new Seq<>();
    /** Prefix used by ore generation**/
    public String orePrefix;

    public SpreadingOverlay(String name, int variants){
        super(name);

        this.variants = variants;
        this.orePrefix = Core.bundle.get(getContentType() + "." + this.name + ".ore-prefix", this.name);

        Events.on(EventType.ModContentLoadEvent.class, e -> {
            generate();

            Core.app.post(() -> {
                if(next instanceof SpreadingOverlay f){
                    for(int i = 0; i < ores.size; i++)
                        ores.get(i).next = f.ores.get(i);

                    return;
                }

                ores.each(o -> o.set = next);
            });
        });

        Events.on(EventType.ServerLoadEvent.class, e ->
            blacklist = blacklist(blacklistKey)
        );
        Events.on(EventType.ClientLoadEvent.class, e -> {
            blacklist = blacklist(blacklistKey);

            int idx = replacements.values().toSeq().indexOf(ores.first());
            Seq<Block> vanilla = replacements.keys().toSeq();

            for(int i = 0; i < ores.size; i++){
                ores.get(i).uiIcon = vanilla.get(i + idx).uiIcon;
                ores.get(i).fullIcon = vanilla.get(i + idx).fullIcon;
                ores.get(i).variants = vanilla.get(i + idx).variants;
                ores.get(i).variantRegions = vanilla.get(i + idx).variantRegions;
                ores.get(i).overlayVariants = variants;
                ores.get(i).overlayRegions = variantRegions;
                ores.get(i).localizedName = Strings.format("[#@]@[] @", mapColor.toString(), orePrefix,  vanilla.get(i + idx).localizedName);
            }
        });
    }

    @Override
    public void init(){
        ObjectSet<Block> list = blacklist(blacklistKey);

        var it = blacklist.iterator();
        while(it.hasNext()){
            Block object = it.next();
            if(!list.contains(object))
                list.add(object);
        }
    }

    @Override
    public boolean isOverlay(){
        return true;
    }

    public void generate(){
        content.blocks().select(b -> b instanceof OreBlock o && !o.wallOre && !(b instanceof SpreadingOre)).each(o -> {
            SpreadingOre ore = new SpreadingOre(getName(o));

            ore.itemDrop = o.itemDrop;
            ore.mapColor.set(o.itemDrop.color).sub(0, 0, 0,  0.45f);

            ore.parent = this;

            replacements.put(o, ore);
            ores.add(ore);
        });
    }

    @Override
    public void drawBase(Tile tile){
        Draw.rect(
            variantRegions[Mathf.randomSeed(tile.pos(), 0, Math.max(0, variantRegions.length - 1))],
            tile.worldx(),
            tile.worldy(),
            Mathf.randomSeed(tile.pos(),0, 3) * 90f
        );
    }

    public String getName(Block in){
        return in.name.replaceAll("ore-|olupis-|nyfalis-", "") + name.replaceAll("olupis|nyfalis|-overlay", "");
    }

    public void updateEnv(Tile tile, int key){
        if(net.client()) return;

        if(Mathf.chance(spreadChance * calyxSpreadingFactor))
            ++data[key][arrayID];

        if(data[key][arrayID] >= spreadTries){
            data[key][arrayID] = 0;

            if(next != null){
                if(upgradeEffect != null){
                    tasks.post(() -> {
                        upgradeEffect.at(tile.worldx(), tile.worldy(), 0f, tile.floor().mapColor, tile.floor());
                        Call.effect(upgradeEffect, tile.worldx(), tile.worldy(), 0, tile.floor().mapColor, tile.floor());
                    });
                }

                if(spreadSound != null)
                    tasks.post(() -> Call.soundAt(spreadSound, tile.worldx(), tile.worldy(), 1f, 1f));

                queue[next.id][arrayID].add(tile.pos());

                if(props.size > 0 && canSpawn(id, propLimit, dynamicLimit) && Mathf.chance(spawnChance)){
                    addProp(id);
                    queue[props.random().id][2].add(tile.pos());
                }
            }

            if(spread && calyxSpreading){
                for(int i = 0; i < 4; i++){
                    Tile near = tile.nearby(i);
                    if(near == null)
                        continue;

                    if(replaces(near)) continue;

                    if(canSpread(near)){
                        if(replacementMap[near.array()][arrayID] <= -1)
                            replacementMap[near.array()][arrayID] = index(near.overlay());
                        queue[id][arrayID].add(near.pos());

                        if(spreadEffect != null){
                            tasks.post(() ->{
                                spreadEffect.at(tile.worldx(), tile.worldy(), near.floor().mapColor);
                                Call.effect(spreadEffect, near.worldx(), near.worldy(), 0, near.floor().mapColor);
                            });
                        }
                    }
                }
            }
        }
    }

    public boolean replaces(Tile tile){
        boolean replaces = false;
        int array = tile.array();
        short id;

        Block block = replacements.get(tile.floor());
        if(block != null){
            replaces = true;

            id = index(tile.floor());
            if(replacementMap[array][0] == -1)
                replacementMap[array][0] = id;
            queue[block.id][0].add(tile.pos());
        }

        block = replacements.get(tile.overlay());
        if(block != null){
            replaces = true;

            id = index(tile.overlay());
            if(replacementMap[array][1] == -1)
                replacementMap[array][1] = id;
            queue[block.id][1].add(tile.pos());
        }

        block = replacements.get(tile.block());
        if(block != null){
            replaces = true;

            id = index(tile.block());
            if(replacementMap[array][2] <= -1)
                replacementMap[array][2] = id;
            queue[block.id][2].add(tile.pos());
        }

        return replaces;
    }

    public boolean canSpread(Tile tile){
        return(
            filter.get(tile.floor())
            && filter.get(tile.overlay())
            && filter.get(tile.block())
        );
    }

    public boolean isValid(Tile tile){
        return(
            validator.get(tile.floor())
            && validator.get(tile.overlay())
            && validator.get(tile.block())
        );
    }

    public Block replacement(){
        return replacement;
    }
}