name: Build Mod

on: [push, pull_request, workflow_call]

jobs:
  buildJar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Hjson
        run: npm install hjson -g
      - name: Convert mod.hjson to mod.json
        run: hjson -j mod.hjson > mod.json
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'mod.json'
          prop_path: 'version'
      - name: Get & shorten SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Override Subtitle w/ Version + Commit
        uses: jossef/action-set-json-field@v2.1
        with:
          file: mod.json
          field: subtitle
          value: " \"${{steps.version.outputs.prop}}-${{steps.short-sha.outputs.sha}}, Yet another planet mod\" "


      - name: Convert mod.json back to mod.hjson
        run: hjson mod.json > mod.hjson

      - name: Build with Gradle
        run: ./gradlew deploy

      - name: Release rename
        run:
          mv build/libs/Olupis-but-a-jar.jar build/libs/${{ github.event.repository.name }}.jar

      - name: Upload built jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar
