name: Send Artifact To Discord

on:
  workflow_run:
    workflows: [Build Mod]
    types: [completed]
    branches: [experimental]
  workflow_call:

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 'Download artifact'
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: deploy.yml
          branch: experimental

      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_NEW }}
          color: "#3ED09A"
          username: "${{github.actor}}"
          message: "> ${{github.event.workflow_run.head_commit.message}}"
          file: "${{ github.event.repository.name }}/${{ github.event.repository.name }}.jar"


  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed sadge'
