name: Send Artifact To Discord

on:
  workflow_run:
    workflows: [Build Mod]
    types: [completed]
    branches: [experimental]
  workflow_call:

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 'Download artifact'
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: deploy.yml
          branch: experimental

      - name: send commit info
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_BETA_CHANNEL_WH }}
          username: ${{github.actor}}
          embed-description: ${{github.event.workflow_run.head_commit.message}}
          embed-color: 4116634
          embed-footer-text: "[link](${{ github.event.workflow_run.head_commit.url}})"
          filename: ${{ github.event.repository.name }}/${{ github.event.repository.name }}.jar


  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed sadge'